POST http://localhost:8081/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNuZWhhQGdtYWlsLmNvbSIsImV4cCI6MTc1NDkzMzEwOSwidXNlcklkIjoyfQ.RGhA0XuSZhokuWdpjipuHx9jsdLYJ2wNrWhDRdXKZso





{
  "NAME": "Open Source Hackathon",
  "DESCRIPTION": "Collaborative coding event focused on open source contributions.",
  "LOCATION": "Remote"
}